name: shopper
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  provider: ^6.0.5
  go_router: ^6.0.7
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.12
  path_provider: ^2.0.12
  path: ^1.8.2
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^8.0.0

  webdav_client: ^1.1.8
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  intl_utils: ^2.8.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
