name: shopper
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  provider: ^6.0.2
  go_router: ^3.0.4
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.4
  path_provider: ^2.0.9
  path: ^1.8.0
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2

  webdav_client: ^1.1.6
  reorderables: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  drift_dev: ^1.4.0
  build_runner: ^2.1.7
  intl_utils: ^2.5.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
