// Mocks generated by Mockito 5.3.2 from annotations
// in shopper/test/features/groceries_list/domain/use_cases/create_groceries_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shopper/src/features/groceries_list/domain/entities/groceries_list.dart'
    as _i2;
import 'package:shopper/src/features/groceries_list/domain/repositories/groceries_list_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGroceriesList_0 extends _i1.SmartFake implements _i2.GroceriesList {
  _FakeGroceriesList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroceriesListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroceriesListRepository extends _i1.Mock
    implements _i3.GroceriesListRepository {
  @override
  _i4.Future<_i2.GroceriesList> createShoppingList({required String? title}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createShoppingList,
          [],
          {#title: title},
        ),
        returnValue: _i4.Future<_i2.GroceriesList>.value(_FakeGroceriesList_0(
          this,
          Invocation.method(
            #createShoppingList,
            [],
            {#title: title},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.GroceriesList>.value(_FakeGroceriesList_0(
          this,
          Invocation.method(
            #createShoppingList,
            [],
            {#title: title},
          ),
        )),
      ) as _i4.Future<_i2.GroceriesList>);
}
